# Generated by Django 2.2 on 2019-04-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datadetailprs',
            fields=[
                ('id_prs', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.TextField(blank=True, null=True)),
                ('kategori_pelanggan', models.IntegerField(blank=True, null=True)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('produksi', models.IntegerField(blank=True, null=True)),
                ('spbg_ngagel', models.IntegerField(blank=True, db_column='SPBG_ngagel', null=True)),
                ('indogas_ikd_porong', models.IntegerField(blank=True, db_column='Indogas_IKD_porong', null=True)),
                ('kso_dg_gagas', models.IntegerField(blank=True, db_column='KSO_DG_Gagas', null=True)),
                ('spbg_purwakarta', models.IntegerField(blank=True, db_column='SPBG_purwakarta', null=True)),
                ('sizegtm', models.TextField(blank=True, db_column='SizeGTM', null=True)),
            ],
            options={
                'db_table': 'datadetailprs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='post_record',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
